### ISSUE TITLE
uncaught exception: Cannot read property 'password' of undefined

### ISSUE THREAD

**Issue by thommycgn** [Apollon77/ioBroker.alexa2#124]
Found this in my logs

```
alexa2.0 | 2018-10-26 14:51:41.020 | info | Alexa-Push-Connection established. Disable Polling
-- | -- | -- | --
alexa2.0 | 2018-10-26 14:51:30.774 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
alexa2.0 | 2018-10-26 14:50:58.818 | warn | Exception: TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2018-10-26 14:50:58.818 | error | TypeError: Cannot read property 'password' of undefined at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:569:53) at /opt/iobroker/node_modules/alexa-remote2/ale
alexa2.0 | 2018-10-26 14:50:58.817 | error | uncaught exception: Cannot read property 'password' of undefined
alexa2.0 | 2018-10-26 14:50:58.817 | warn | Exception: TypeError: Cannot read property 'password' of undefined
alexa2.0 | 2018-10-26 14:50:58.817 | error | TypeError: Cannot read property 'password' of undefined at checkAuthentication (/opt/iobroker/node_modules/alexa-remote2/alexa-remote.js:569:53) at /opt/iobroker/node_modules/alexa-remote2/ale
alexa2.0 | 2018-10-26 14:50:58.816 | error | uncaught exception: Cannot read property 'password' of undefined


```

**Comment by Ilovegym66** [comment]
hatte ich heute auch, Adapter stand auf einmal auf Gelb, ein Neustart nur des Adapters hat aber geholfen.
Hier das Log dazu, anscheinend ein Problem mit Amazon Port 443.. 
`2018-11-01 13:41:49.634  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-01 13:42:14.659  - info: alexa2.0 Alexa-Push-Connection Error: Error: getaddrinfo EAI_AGAIN dp-gw-na.amazon.de:443
2018-11-01 13:42:14.659  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-01 13:42:44.194  - info: alexa2.0 Alexa-Push-Connection Error: Error: getaddrinfo EAI_AGAIN dp-gw-na.amazon.de:443
2018-11-01 13:42:44.194  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-01 13:43:09.216  - info: alexa2.0 Alexa-Push-Connection Error: Error: getaddrinfo EAI_AGAIN dp-gw-na.amazon.de:443
2018-11-01 13:43:09.216  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-01 13:43:31.242  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-11-01 13:43:31.243  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:569:53)
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:677:20
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:661:24)
2018-11-01 13:43:31.244  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2018-11-01 13:43:31.245  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-11-01 13:43:31.245  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:569:53)
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:677:20
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:661:24)
2018-11-01 13:43:31.245  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2018-11-01 13:43:34.249  - error: Caught by controller[0]:     at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:569:53)
2018-11-01 13:43:34.249  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:677:20
2018-11-01 13:43:34.249  - error: Caught by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:661:24)
2018-11-01 13:43:34.249  - error: Caught by controller[1]:     at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:569:53)
2018-11-01 13:43:34.249  - error: Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:677:20
2018-11-01 13:43:34.249  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:661:24)
2018-11-01 13:43:34.250  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 13:43:34.250  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-01 13:44:04.257  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4762
2018-11-01 13:44:04.658  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 13:44:45.472  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:44:45.472  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:44:45.473  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:44:45.475  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:44:45.475  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:44:45.475  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:44:45.486  - error: Caught by controller[0]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:44:45.486  - error: Caught by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:44:45.486  - error: Caught by controller[1]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:44:45.486  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:44:45.487  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 13:44:45.487  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-01 13:45:15.494  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4772
2018-11-01 13:45:15.902  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 13:45:56.309  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:45:56.309  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:45:56.310  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:45:56.311  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:45:56.312  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:45:56.312  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:45:56.324  - error: Caught by controller[0]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:45:56.324  - error: Caught by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:45:56.325  - error: Caught by controller[1]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:45:56.325  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:45:56.325  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 13:45:56.325  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-01 13:46:26.332  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4782
2018-11-01 13:46:26.740  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 13:47:07.177  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:47:07.177  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:47:07.178  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:47:07.179  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:47:07.180  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:47:07.180  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:47:07.191  - error: Caught by controller[0]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:47:07.191  - error: Caught by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:47:07.192  - error: Caught by controller[1]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:47:07.192  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:47:07.192  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 13:47:07.192  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-01 13:47:37.235  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4797
2018-11-01 13:47:37.650  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 13:48:18.057  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:48:18.058  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:48:18.058  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:48:18.060  - error: alexa2.0 uncaught exception: Cannot read property 'options' of undefined
2018-11-01 13:48:18.060  - error: alexa2.0 TypeError: Cannot read property 'options' of undefined
    at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:48:18.061  - warn: alexa2.0 Exception: TypeError: Cannot read property 'options' of undefined
2018-11-01 13:48:18.070  - error: Caught by controller[0]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:48:18.071  - error: Caught by controller[0]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:48:18.071  - error: Caught by controller[1]:     at request (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:236:72)
2018-11-01 13:48:18.071  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-cookie2/alexa-cookie.js:114:24)
2018-11-01 13:48:18.071  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 13:48:18.071  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-01 13:48:48.079  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4807
2018-11-01 13:48:48.492  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 13:49:16.782  - error: alexa2.0 Error: Amazon-Login-Error: Wichtige Mitteilung!: Zum besseren Schutz Ihres Kontos geben Sie bitte nochmals Ihr Passwort ein, und geben Sie dann die Zeichen ein, die in der Abbildung unten gezeigt werden. 
2018-11-01 13:49:16.782  - error: alexa2.0 Error: You can try to get the cookie manually by opening http://192.168.178.41:39309/ with your browser.
2018-11-01 14:04:14.061  - info: host.iobroker object change system.adapter.alexa2.0
2018-11-01 14:04:14.061  - info: host.iobroker stopInstance system.adapter.alexa2.0
2018-11-01 14:04:14.061  - info: host.iobroker stopInstance system.adapter.alexa2.0 killing pid 4807
2018-11-01 14:04:14.086  - info: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-01 14:04:16.570  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 4922
2018-11-01 14:04:16.992  - info: alexa2.0 starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-01 14:04:22.374  - info: alexa2.0 Alexa-Push-Connection established. Disable Polling
`

**Comment by Ilovegym66** [comment]
Da hatte wahrscheinlich Amazon ein Problem und auf meinem Rechner war der Browser durcheinander gekommen, nach dem löschen des Caches ging ein von zwei Accounts wieder. Das unangenehme war, dass der Adapter anscheinend das falsche Cookie nahm .. ich hatte in meinem Amazon-Account nur die Geräte von meiner Mutter, und ihr Adapter lief auch mit ihren Echos, bei mir hageltes es dann Fehlermeldungen weil meine Geräte ja nicht da waren... 

Nach einem Reboot, löschen des Caches von Firefox und Chrome, lief auf einmal der Adapter gar nicht mehr. 
Habe jedem Account / Instanz einen festen Proxyport zugewiesen.
Meinen Cookie dann über Firefox geholt, und den von meiner Mutter dann über Chrome.
Das hat funktioniert.. 

Bin mal gespannt, wie das nächste Woche, wenn die cookies ablaufen, aussieht..

**Comment by Apollon77** [comment]
retry 2,.1 vom Github
