### ISSUE TITLE
Internet dis- und reconnect bleibt Adapter auf gelb

### ISSUE THREAD

**Issue by Ilovegym66** [Apollon77/ioBroker.alexa2#148]
Hi, 
erstmal Danke für die viele viele Arbeit und den tollen Adapter!
Leider ist seit Version 1.x ( aktuell installiert 1.1.3 ) es so, dass bei einem längerem disconnect der Internet Verbindung der Adapter auf gelb geht, wie der Cloud-Adapter auch, aber bei wiederhergestellter Verbindung dann so stehen bleibt. Der Cloud Adapter wird dann wieder grün.. 
Ein einfacher Adapter-Restart in den Instanzen erweckt ihn wieder zu leben und alles ist gut.
Hat also nix mit Plätzchen zu tun :-) 

Habe das auch nur durch Zufall gemerkt, da ich meine Fritzbox im Haus an einen anderen Ort platziert habe.

**Comment by Apollon77** [comment]
Hast Du mal den Log-Output von so einem Fall?

**Comment by Ilovegym66** [comment]
steht jetzt nicht auf debug, aber hilft hoffentlich trotzdem, der Unterschied zu Nachts, wo die Zwangstrennung stattfindet, ist die Zeitdauer.
Hier das Log von der Zwangstrennung, danach läuft er wieder von alleine einwandfrei:
`2018-11-21 02:54:14.274  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-21 02:54:19.977  - info: alexa2.0 Alexa-Push-Connection established. Disable Polling
2018-11-21 02:54:44.291  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-21 02:54:50.023  - info: alexa2.0 Alexa-Push-Connection established. Disable Polling
`

und jetzt hier die Trennung nach bösartigem Disconnect meinerseits :-) mit längerer Dauer ( ca. 20min..)
`2018-11-21 12:46:50.561  - info: alexa2.0 Alexa-Push-Connection disconnected - retry: Retry Connection in 5s
2018-11-21 12:47:12.588  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-11-21 12:47:12.589  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
2018-11-21 12:47:12.590  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2018-11-21 12:47:12.591  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-11-21 12:47:12.592  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
2018-11-21 12:47:12.592  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2018-11-21 12:47:15.598  - error: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-21 12:47:15.598  - info: host.iobroker Restart adapter system.adapter.alexa2.0 because enabled
2018-11-21 12:47:45.608  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 25087
2018-11-21 12:47:45.964  - info: alexa2.0 starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-21 12:48:26.443  - error: alexa2.0 Error: getaddrinfo EAI_AGAIN alexa.amazon.de:443
2018-11-21 14:56:22.023  - info: host.iobroker object change system.adapter.alexa2.0
2018-11-21 14:56:22.024  - info: host.iobroker stopInstance system.adapter.alexa2.0
2018-11-21 14:56:22.024  - info: host.iobroker stopInstance system.adapter.alexa2.0 killing pid 25087
2018-11-21 14:56:22.057  - info: host.iobroker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2018-11-21 14:56:24.538  - info: host.iobroker instance system.adapter.alexa2.0 started with pid 25547
2018-11-21 14:56:24.939  - info: alexa2.0 starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.12.0
2018-11-21 14:56:31.969  - info: alexa2.0 Alexa-Push-Connection established. Disable Polling
`
zum Vergleich hier die logs vom Cloud-Adapter, hier Zwangstrennung:
`2018-11-21 02:53:59.900  - info: cloud.0 Connection changed: transport close
2018-11-21 02:53:59.900  - info: cloud.0 Connection lost
2018-11-21 02:54:09.916  - error: host.iobroker instance system.adapter.cloud.0 terminated with code 156 ()
2018-11-21 02:54:09.916  - info: host.iobroker Restart adapter system.adapter.cloud.0 because enabled
2018-11-21 02:54:39.928  - info: host.iobroker instance system.adapter.cloud.0 started with pid 21132
2018-11-21 02:54:40.376  - info: cloud.0 starting. Version 2.7.1 in /opt/iobroker/node_modules/iobroker.cloud, node: v8.12.0
2018-11-21 02:54:40.437  - info: cloud.0 Connecting with https://iobroker.pro:10555 with "@pro_berndhassenzahl@gehtniemandwasan"
2018-11-21 02:54:41.215  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 02:55:40.450  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 02:55:40.510  - info: cloud.0 Connection changed: connect
2018-11-21 02:55:40.524  - info: cloud.0 Connection not changed: was connected
`

und jetzt der cloud-Adapter bei bösartigem Trennen :-)
`2018-11-21 12:43:16.836  - error: cloud.0 Ping timeout
2018-11-21 12:43:16.837  - info: cloud.0 Connection changed: Ping timeout
2018-11-21 12:43:16.837  - info: cloud.0 Connection lost
2018-11-21 12:43:26.838  - info: cloud.0 Connection changed: io client disconnect
2018-11-21 12:43:26.853  - error: host.iobroker instance system.adapter.cloud.0 terminated with code 156 ()
2018-11-21 12:43:26.853  - info: host.iobroker Restart adapter system.adapter.cloud.0 because enabled
2018-11-21 12:43:56.867  - info: host.iobroker instance system.adapter.cloud.0 started with pid 25051
2018-11-21 12:43:57.390  - info: cloud.0 starting. Version 2.7.1 in /opt/iobroker/node_modules/iobroker.cloud, node: v8.12.0
2018-11-21 12:43:57.476  - info: cloud.0 Connecting with https://iobroker.pro:10555 with "@pro_berndhassenzahl@gehtniemandwasan"
2018-11-21 12:43:58.228  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:44:07.498  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:44:57.488  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:45:07.485  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:45:57.491  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:46:07.488  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:46:57.494  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:47:07.491  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:47:57.502  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:48:07.491  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:48:57.497  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:49:07.495  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:49:57.499  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:50:07.498  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:50:57.501  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:51:07.500  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:51:57.504  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:52:07.501  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:52:57.505  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:53:07.502  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:53:57.508  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:54:07.506  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 12:54:57.512  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 12:54:57.667  - info: cloud.0 Connection changed: connect
2018-11-21 12:54:57.681  - info: cloud.0 Connection not changed: was connected
2018-11-21 14:20:02.891  - error: cloud.0 Ping timeout
2018-11-21 14:20:02.891  - info: cloud.0 Connection changed: Ping timeout
2018-11-21 14:20:02.891  - info: cloud.0 Connection lost
2018-11-21 14:20:12.894  - info: cloud.0 Connection changed: io client disconnect
2018-11-21 14:20:12.916  - error: host.iobroker instance system.adapter.cloud.0 terminated with code 156 ()
2018-11-21 14:20:12.916  - info: host.iobroker Restart adapter system.adapter.cloud.0 because enabled
2018-11-21 14:20:42.929  - info: host.iobroker instance system.adapter.cloud.0 started with pid 25377
2018-11-21 14:20:43.490  - info: cloud.0 starting. Version 2.7.1 in /opt/iobroker/node_modules/iobroker.cloud, node: v8.12.0
2018-11-21 14:20:43.558  - info: cloud.0 Connecting with https://iobroker.pro:10555 with "@pro_berndhassenzahl-gehtniemandwasan"
2018-11-21 14:20:44.184  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:20:53.577  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:21:43.570  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:21:53.567  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:22:43.574  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:22:53.570  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:23:43.576  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:23:53.573  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:24:43.580  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:24:53.575  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:25:43.581  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:25:53.578  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:26:43.583  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:26:53.581  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:27:43.588  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:27:53.584  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:28:43.589  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:28:53.586  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:29:43.590  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:29:43.664  - info: cloud.0 Connection changed: connect
2018-11-21 14:29:43.678  - info: cloud.0 Connection not changed: was connected
2018-11-21 14:30:48.665  - error: cloud.0 Ping timeout
2018-11-21 14:30:48.665  - info: cloud.0 Connection changed: Ping timeout
2018-11-21 14:30:48.666  - info: cloud.0 Connection lost
2018-11-21 14:30:58.668  - info: cloud.0 Connection changed: io client disconnect
2018-11-21 14:30:58.679  - error: host.iobroker instance system.adapter.cloud.0 terminated with code 156 ()
2018-11-21 14:30:58.679  - info: host.iobroker Restart adapter system.adapter.cloud.0 because enabled
2018-11-21 14:31:28.693  - info: host.iobroker instance system.adapter.cloud.0 started with pid 25464
2018-11-21 14:31:29.154  - info: cloud.0 starting. Version 2.7.1 in /opt/iobroker/node_modules/iobroker.cloud, node: v8.12.0
2018-11-21 14:31:29.218  - info: cloud.0 Connecting with https://iobroker.pro:10555 with "@pro_berndhassenzahl@gehtniemandwasan"
2018-11-21 14:31:29.993  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:31:39.238  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:32:29.229  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:32:39.225  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:33:29.234  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:33:39.229  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:34:29.236  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:34:39.233  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:35:29.238  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:35:39.235  - error: cloud.0 Error while connecting to cloud: timeout
2018-11-21 14:36:29.239  - info: cloud.0 Trying to connect as system.user.admin
2018-11-21 14:36:29.345  - info: cloud.0 Connection changed: connect
2018-11-21 14:36:29.359  - info: cloud.0 Connection not changed: was connected
`

**Comment by Apollon77** [comment]
```
2019-01-22 17:06:39.967  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2019-01-22 17:06:39.972  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:634:52)
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:742:20
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:726:24)
2019-01-22 17:06:39.977  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2019-01-22 17:06:39.980  - error: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2019-01-22 17:06:39.981  - error: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:634:52)
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:742:20
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:726:24)
2019-01-22 17:06:39.981  - warn: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2019-01-22 17:06:39.987  - info: alexa2.0 terminating
2019-01-22 17:06:40.047  - error: Caught by controller[1]:     at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:634:52)
2019-01-22 17:06:40.048  - error: Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:742:20
2019-01-22 17:06:40.048  - error: Caught by controller[1]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:726:24)
2019-01-22 17:06:40.049  - error: Caught by controller[2]:     at checkAuthentication (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:634:52)
2019-01-22 17:06:40.049  - error: Caught by controller[2]:     at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:742:20
2019-01-22 17:06:40.050  - error: Caught by controller[2]:     at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:726:24)
2019-01-22 17:06:40.051  - error: host.io1 instance system.adapter.alexa2.0 terminated with code 0 (OK)
2019-01-22 17:06:40.051  - info: host.io1 Restart adapter system.adapter.alexa2.0 because enabled
2019-01-22 17:07:10.082  - info: host.io1 instance system.adapter.alexa2.0 started with pid 6983
2019-01-22 17:07:11.329  - info: alexa2.0 States connected to redis: 192.168.178.48:6379
2019-01-22 17:07:11.398  - info: alexa2.0 starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.alexa2, node: v6.16.0
2019-01-22 17:08:18.035  - error: alexa2.0 Error: 
2019-01-22 17:08:18.036  - error: alexa2.0 Error: You can try to get the cookie manually by opening http://192.168.178.48:42549/ with your browser.

```

**Comment by henkhb** [comment]
Gibts hier schon was neues? Leider auch hier ein nerviges Problem!
Danke für Deine Arbeit!

**Comment by Apollon77** [comment]
Ich brauche einen neuen Fall inklusive Error log mit der aktuellen 2.3.3 :-( chhabe getestet. Wenn ich WLAN weg nehme dann gibt es nur timeouts und die werden korrekt behandelt. Also ginge es darum das ggf DNS nicht korrekt aufgelöst werden kann ...

**Comment by Apollon77** [comment]
Habe was geändert, ist in 2.4.1 drin, später heute auf Github
