### ISSUE TITLE
uncaught exception: Cannot read property 'mediaProgress' of null

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.alexa2#258]
```
alexa2.0	2019-06-24 09:57:40.478	info	Alexa-Push-Connection established. Disable Polling
alexa2.0	2019-06-24 09:57:35.378	info	starting. Version 2.4.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v6.16.0
host.ioBroker-Tinker	2019-06-24 09:57:34.343	info	instance system.adapter.alexa2.0 started with pid 16433
host.ioBroker-Tinker	2019-06-24 09:57:04.320	info	Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker-Tinker	2019-06-24 09:57:04.320	error	instance system.adapter.alexa2.0 terminated with code 0 (OK)
Caught	2019-06-24 09:57:04.319	error	by controller[0]: at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/receiver.js:413:14)
Caught	2019-06-24 09:57:04.319	error	by controller[0]: at Receiver.emit (events.js:188:7)
Caught	2019-06-24 09:57:04.319	error	by controller[0]: at emitOne (events.js:96:13)
Caught	2019-06-24 09:57:04.319	error	by controller[0]: at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:789:20)
Caught	2019-06-24 09:57:04.319	error	by controller[0]: at WebSocket.emit (events.js:188:7)
Caught	2019-06-24 09:57:04.318	error	by controller[0]: at emitOne (events.js:96:13)
Caught	2019-06-24 09:57:04.318	error	by controller[0]: at WebSocket.websocket.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-wsmqtt.js:202:22)
Caught	2019-06-24 09:57:04.318	error	by controller[0]: at AlexaWsMqtt.emit (events.js:191:7)
Caught	2019-06-24 09:57:04.318	error	by controller[0]: at emitTwo (events.js:106:13)
Caught	2019-06-24 09:57:04.318	error	by controller[0]: at AlexaWsMqtt.alexaWsMqtt.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:471:56)
Caught	2019-06-24 09:57:04.317	error	by controller[0]: TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:57:04.265	warn	Exception: TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:57:04.261	error	at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/receiver.js:413:14)
alexa2.0	2019-06-24 09:57:04.261	error	at Receiver.emit (events.js:188:7)
alexa2.0	2019-06-24 09:57:04.261	error	at emitOne (events.js:96:13)
alexa2.0	2019-06-24 09:57:04.261	error	at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:789:20)
alexa2.0	2019-06-24 09:57:04.261	error	at WebSocket.emit (events.js:188:7)
alexa2.0	2019-06-24 09:57:04.261	error	at emitOne (events.js:96:13)
alexa2.0	2019-06-24 09:57:04.261	error	at WebSocket.websocket.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-wsmqtt.js:202:22)
alexa2.0	2019-06-24 09:57:04.261	error	at AlexaWsMqtt.emit (events.js:191:7)
alexa2.0	2019-06-24 09:57:04.261	error	at emitTwo (events.js:106:13)
alexa2.0	2019-06-24 09:57:04.261	error	at AlexaWsMqtt.alexaWsMqtt.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:471:56)
alexa2.0	2019-06-24 09:57:04.261	error	TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:57:04.260	error	uncaught exception: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:56:46.622	info	Alexa-Push-Connection established. Disable Polling
alexa2.0	2019-06-24 09:56:41.115	info	starting. Version 2.4.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v6.16.0
host.ioBroker-Tinker	2019-06-24 09:56:39.993	info	instance system.adapter.alexa2.0 started with pid 16405
host.ioBroker-Tinker	2019-06-24 09:56:09.953	info	Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker-Tinker	2019-06-24 09:56:09.953	error	instance system.adapter.alexa2.0 terminated with code 0 (OK)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/receiver.js:413:14)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at Receiver.emit (events.js:188:7)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at emitOne (events.js:96:13)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:789:20)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at WebSocket.emit (events.js:188:7)
Caught	2019-06-24 09:56:09.953	error	by controller[0]: at emitOne (events.js:96:13)
Caught	2019-06-24 09:56:09.952	error	by controller[0]: at WebSocket.websocket.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-wsmqtt.js:202:22)
Caught	2019-06-24 09:56:09.952	error	by controller[0]: at AlexaWsMqtt.emit (events.js:191:7)
Caught	2019-06-24 09:56:09.952	error	by controller[0]: at emitTwo (events.js:106:13)
Caught	2019-06-24 09:56:09.951	error	by controller[0]: at AlexaWsMqtt.alexaWsMqtt.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:471:56)
Caught	2019-06-24 09:56:09.947	error	by controller[0]: TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:56:09.856	warn	Exception: TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:56:09.843	error	at Receiver.dataMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/receiver.js:413:14)
alexa2.0	2019-06-24 09:56:09.843	error	at Receiver.emit (events.js:188:7)
alexa2.0	2019-06-24 09:56:09.843	error	at emitOne (events.js:96:13)
alexa2.0	2019-06-24 09:56:09.843	error	at Receiver.receiverOnMessage (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/ws/lib/websocket.js:789:20)
alexa2.0	2019-06-24 09:56:09.843	error	at WebSocket.emit (events.js:188:7)
alexa2.0	2019-06-24 09:56:09.843	error	at emitOne (events.js:96:13)
alexa2.0	2019-06-24 09:56:09.843	error	at WebSocket.websocket.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-wsmqtt.js:202:22)
alexa2.0	2019-06-24 09:56:09.843	error	at AlexaWsMqtt.emit (events.js:191:7)
alexa2.0	2019-06-24 09:56:09.843	error	at emitTwo (events.js:106:13)
alexa2.0	2019-06-24 09:56:09.843	error	at AlexaWsMqtt.alexaWsMqtt.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:471:56)
alexa2.0	2019-06-24 09:56:09.843	error	TypeError: Cannot read property 'mediaProgress' of null
alexa2.0	2019-06-24 09:56:09.830	error	uncaught exception: Cannot read property 'mediaProgress' of null
```

**Comment by Apollon77** [comment]
fixed by 2.4.3 on npm, so latest soon (or GitHub)
