### ISSUE TITLE
2.6.1 issue

### ISSUE THREAD

**Issue by vr6syncro** [Apollon77/ioBroker.alexa2#279]
`

host.ioBroker | 2019-07-24 17:31:01.300 | info | iobroker npm notice created a lockfile as package-lock.json. You should commit this file.
-- | -- | -- | --
host.ioBroker | 2019-07-24 17:30:48.828 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker | 2019-07-24 17:30:48.828 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:63:19)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1129:12)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:203:15)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at IncomingMessage.res.on (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:749:62)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:1208:17
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: at alexa.getContacts (/opt/iobroker/node_modules/iobroker.alexa2/main.js:2064:30)
host.ioBroker | 2019-07-24 17:30:48.828 | error | Caught by controller[0]: TypeError: commContacts.forEach is not a function
alexa2.0 | 2019-07-24 17:30:48.793 | error | TypeError: commContacts.forEach is not a function at alexa.getContacts (/opt/iobroker/node_modules/iobroker.alexa2/main.js:2064:30) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/a
alexa2.0 | 2019-07-24 17:30:48.793 | error | uncaught exception: commContacts.forEach is not a function
alexa2.0 | 2019-07-24 17:30:48.793 | warn | Exception: TypeError: commContacts.forEach is not a function

`

**Comment by Apollon77** [comment]
Bitte 2.6.2 vom GitHub versuchen

**Comment by vr6syncro** [comment]
konnte nur 2.6.4 testen aber damit ist es nicht mehr vorhanden.

**Comment by TQ-Airman** [comment]
Leider kann ich das nicht bestätigen.
Sobald ich den "Echo Dot" aktiviere kommen die Fehlermeldungen mit dem Echo Dot 2 allein ist alles OK
Bei mir ist die Admin Version 3.6.7 und die Alexa2 Version 2.6.4 und die Fehlermeldung sieht wie folgt aus:

2019-10-03 10:25:10.497 - info: alexa2.0 terminating
--
2019-10-03 10:25:10.538 - error: Caught by controller[0]: TypeError: native.valueMap.indexOf is not a function
2019-10-03 10:25:10.538 - error: Caught by controller[0]: at handleObject (/opt/iobroker/node_modules/iobroker.alexa2/main.js:748:37)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at updateSmarthomeDeviceStates (/opt/iobroker/node_modules/iobroker.alexa2/main.js:792:46)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at alexa.querySmarthomeDevices (/opt/iobroker/node_modules/iobroker.alexa2/main.js:607:13)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at IncomingMessage.res.on.e (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:752:58)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at emitNone (events.js:91:20)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at IncomingMessage.emit (events.js:185:7)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at endReadableNT (_stream_readable.js:978:12)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:80:11)
2019-10-03 10:25:10.539 - error: Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:104:9)
2019-10-03 10:25:10.539 - error: host.ioBroker-Tinker instance system.adapter.alexa2.0 terminated with code 0 (OK)
2019-10-03 10:25:10.540 - info: host.ioBroker-Tinker Restart adapter system.adapter.alexa2.0 because enabled

Sobald ich den "Echo DOT" wieder ausschalte ist alles OK
