### ISSUE TITLE
Crashes after updating to Node 14 / JS-Controller 3.0.17

### ISSUE THREAD

**Issue by AlCalzone** [Apollon77/ioBroker.alexa2#441]
```

2020-04-23 19:43:21.403  - info: host.Heizung compactgroup controller 1 terminated
--
2020-04-23 19:43:21.476  - error: host.Heizung Caught by controller[0]: Cannot read property 'end' of null
2020-04-23 19:43:21.477  - error: host.Heizung Caught by controller[1]: TypeError: Cannot read property 'end' of null
2020-04-23 19:43:21.478  - error: host.Heizung Caught by controller[1]:     at IncomingMessage. (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
2020-04-23 19:43:21.478  - error: host.Heizung Caught by controller[1]:     at IncomingMessage.emit (events.js:327:22)
2020-04-23 19:43:21.479  - error: host.Heizung Caught by controller[1]:     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
2020-04-23 19:43:21.480  - error: host.Heizung Caught by controller[1]:     at endReadableNT (_stream_readable.js:1218:12)
2020-04-23 19:43:21.481  - error: host.Heizung Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-04-23 19:43:21.481  - error: host.Heizung Caught by controller[2]: TypeError: Cannot read property 'end' of null
2020-04-23 19:43:21.482  - error: host.Heizung Caught by controller[2]:     at IncomingMessage. (/opt/iobroker/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
2020-04-23 19:43:21.483  - error: host.Heizung Caught by controller[2]:     at IncomingMessage.emit (events.js:327:22)
2020-04-23 19:43:21.483  - error: host.Heizung Caught by controller[2]:     at IncomingMessage.EventEmitter.emit (domain.js:485:12)
2020-04-23 19:43:21.484  - error: host.Heizung Caught by controller[2]:     at endReadableNT (_stream_readable.js:1218:12)
2020-04-23 19:43:21.484  - error: host.Heizung Caught by controller[2]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-04-23 19:43:21.487  - info: host.Heizung Restart compact group controller 1

```

**Comment by Apollon77** [comment]
fixed in 3.2.0
