### ISSUE TITLE
Expired cookie causes crash

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa2#57]
```
2018-08-02 20:17:27.064  - ESC[31merrorESC[39m: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-08-02 20:17:27.070  - ESC[31merrorESC[39m: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:52
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1296:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
2018-08-02 20:17:27.072  - ESC[33mwarnESC[39m: alexa2.0 Exception: TypeError: Cannot read property 'password' of undefined
2018-08-02 20:17:27.075  - ESC[31merrorESC[39m: alexa2.0 uncaught exception: Cannot read property 'password' of undefined
2018-08-02 20:17:27.075  - ESC[31merrorESC[39m: alexa2.0 TypeError: Cannot read property 'password' of undefined
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:283:52
    at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:392:16
    at ClientRequest.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/alexa-remote2/alexa-remote.js:377:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketCloseListener (_http_client.js:286:9)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:509:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```

**Comment by Apollon77** [comment]
recheck with 0.4.0 on next cookie update
