### ISSUE TITLE
Fehler beim Steuern eines Smart home devices 0.6.1

### ISSUE THREAD

**Issue by timae146** [Apollon77/ioBroker.alexa2#79]
-> Adapter startet neu.

alexa2.0 | 2018-08-26 18:18:17.119 | info | starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.alexa2, node: v8.11.1
-- | -- | -- | --
host.ioBroker-RasPi | 2018-08-26 18:18:15.666 | info | instance system.adapter.alexa2.0 started with pid 16521
host.ioBroker-RasPi | 2018-08-26 18:17:45.642 | info | Restart adapter system.adapter.alexa2.0 because enabled
host.ioBroker-RasPi | 2018-08-26 18:17:45.641 | error | instance system.adapter.alexa2.0 terminated with code 0 (OK)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at processImmediate [as _immediateCallback] (timers.js:729:5)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at tryOnImmediate (timers.js:752:5)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at runCallback (timers.js:794:20)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3725:38)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at Adapter.emit (events.js:214:7)
Caught | 2018-08-26 18:17:45.641 | error | by controller[0]:     at emitTwo (events.js:126:13)
Caught | 2018-08-26 18:17:45.640 | error | by controller[0]:     at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.alexa2/main.js:297:31)
Caught | 2018-08-26 18:17:45.640 | error | by controller[0]:     at AlexaRemote.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:724:64)
Caught | 2018-08-26 18:17:45.640 | error | by controller[0]:     at buildSmartHomeControlParameters (/opt/iobroker/node_modules/iobroker.alexa2/main.js:525:21)
Caught | 2018-08-26 18:17:45.639 | error | by controller[0]: TypeError: objs is not iterable
alexa2.0 | 2018-08-26 18:17:45.611 | info | terminating
alexa2.0 | 2018-08-26 18:17:45.604 | warn | Exception: TypeError: objs is not iterable
alexa2.0 | 2018-08-26 18:17:45.600 | error | at processImmediate [as _immediateCallback] (timers.js:729:5)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at tryOnImmediate (timers.js:752:5)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at runCallback (timers.js:794:20)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3725:38)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at Adapter.emit (events.js:214:7)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at emitTwo (events.js:126:13)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.alexa2/main.js:297:31)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at AlexaRemote.<anonymous> (/opt/iobroker/node_modules/iobroker.alexa2/main.js:724:64)
alexa2.0 | 2018-08-26 18:17:45.600 | error | at buildSmartHomeControlParameters (/opt/iobroker/node_modules/iobroker.alexa2/main.js:525:21)
alexa2.0 | 2018-08-26 18:17:45.600 | error | TypeError: objs is not iterable
alexa2.0 | 2018-08-26 18:17:45.599 | error | uncaught exception: objs is not iterable
alexa2.0 | 2018-08-26 18:17:45.572 | debug | State changed  alexa2.0.Smart-Home-Devices.fb226f27-9c76-4bf4-8a20-de2ae6cac98f.powerState:   {"val":false,"ack":false,"ts":1535300265569,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin"

**Comment by timae146** [comment]
Kommando zurück. hatte wohl noch eine alte 0.6.1er version installiert. kann geschlossen werden. 👍
