### ISSUE TITLE
Many errors since i woke up

### ISSUE THREAD

**Issue by vaaarg** [Apollon77/ioBroker.alexa2#914]
Flooding of errors occured 2 times this night. at 4 and 6 oclock as the alexa alarm clock goes on. possibly something to do with that ?

Restart of instance at debug level shows no errors (feels like it generates one million entries within minutes)

alexa 3.15.2
jscontroller 4.0.23
linux
CPUs4
Geschwindigkeit1500 MHz
ModellARMv7 Processor rev 3 (v7l)
RAM3.75 GB
Node.jsv14.20.0 (Empfohlene Version v16.16.0)
Anzahl der Adapter501
NPM6.14.17
Aktive Instanzen20

`host.pio4gb
2022-07-11 06:15:19.859	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:15:19.859	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:15:19.859	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:15:19.859	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:15:19.859	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:15:19.859	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:15:19.858	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:15:19.858	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:15:19.858	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:15:19.858	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:15:19.858	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:15:19.857	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:15:19.557	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:15:19.556	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:15:19.556	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:15:00.164	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:15:00.164	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:15:00.164	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:15:00.164	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:15:00.164	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:15:00.164	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:15:00.163	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:15:00.163	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:15:00.163	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:15:00.163	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:15:00.163	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:15:00.162	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:59.891	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:59.891	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:14:59.890	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:14:40.011	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:14:40.011	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:14:40.011	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:14:40.011	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:14:40.011	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:14:40.010	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:14:40.009	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:39.741	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:39.740	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:14:39.740	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:14:19.959	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:14:19.959	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:14:19.959	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:14:19.959	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:14:19.959	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:14:19.959	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:14:19.958	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:14:19.958	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:14:19.958	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:14:19.958	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:14:19.958	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:14:19.957	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:19.632	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:14:19.632	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:14:19.631	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:13:59.792	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:13:59.792	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:13:59.792	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:13:59.792	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:13:59.791	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:13:59.790	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:13:59.790	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:13:59.495	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:13:59.494	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:13:59.493	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:13:40.031	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:13:40.030	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:13:40.029	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:13:40.029	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:13:40.029	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27
host.pio4gb
2022-07-11 06:13:40.029	error	Caught by controller[0]: TypeError: Cannot read property '1' of null

alexa2.0
2022-07-11 06:13:39.772	error	Cannot read property '1' of null

alexa2.0
2022-07-11 06:13:39.771	error	TypeError: Cannot read property '1' of null at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:133:27 at Array.map (<anonymous>) at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29 at Array.forEach (<anonymous>) at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9) at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14) at Array.map (<anonymous>) at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41) at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24

alexa2.0
2022-07-11 06:13:39.771	error	uncaught exception: Cannot read property '1' of null
host.pio4gb
2022-07-11 06:13:20.216	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/rrulestr.ts:50:24
host.pio4gb
2022-07-11 06:13:20.216	error	Caught by controller[0]: at parseString (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:7:41)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at parseLine (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:42:14)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at Array.forEach (<anonymous>)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at parseWeekday (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:125:15)
host.pio4gb
2022-07-11 06:13:20.216	error	instance system.adapter.alexa2.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at Array.map (<anonymous>)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:82:29
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at parseRrule (/opt/iobroker/node_modules/iobroker.alexa2/node_modules/rrule/dist/es5/webpack:/rrule/src/parsestring.ts:56:9)
host.pio4gb
2022-07-11 06:13:20.215	error	Caught by controller[0]: at Array.map (<anonymous>)
`

**Comment by Apollon77** [comment]
Hmm... Please set the loglevel of the instance to Debug and send me a full debug log from start to this crash. It seems that one Timer/Alarm/Reminder contains strange values that causes this ... Get the log from logfile on disk (/opt/iobroker/log/...). end with refernce to this issue to iobroker@fischer-ka.de

**Comment by Apollon77** [comment]
PS: Or if it has something to do with an alarm that goes on then please try to produce such a situation and include in the log

**Comment by Apollon77** [comment]
Ok  ich denke ich brauche keinen Log ... waren bestimmt alles einmalige Wecker? Wird in kommender Version gefixt sein
