### ISSUE TITLE
Update 3.19.9 auf 3.19.10: npm ERR! code ETARGET

### ISSUE THREAD

**Issue by Horgul123** [Apollon77/ioBroker.alexa2#971]
Beim Versuch den Adpater von 3.19.9 auf 3.19.10 zu aktualisieren bekomme ich einen
npm ERR! code ETARGET

js-controller 4.0.23
Node.js: v16.16.0
NPM: 8.11.0
Debian 11

Brauchst Du noch mehr Infos? Welche?

`$ iobroker upgrade alexa2@3.19.10 --debug

Update alexa2 from @3.19.9 to @3.19.10

NPM version: 8.11.0Installing iobroker.alexa2@3.19.10... (System call)

npm ERR! code ETARGET

upload [28] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/alexa.png alexa.png image/png

upload [20] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_dot3.png icons/echo_dot3.png image/png

upload [12] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/echo_sub.png icons/echo_sub.png image/png

upload [6] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/icons/reverb.png icons/reverb.png image/png

upload [1] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/warning.png warning.png image/png

upload [0] alexa2.admin /opt/iobroker/node_modules/iobroker.alexa2/admin/words.js words.js application/javascript

Process exited with code 0

`

**Comment by Obast** [comment]
same here...

relevant part of extended log shows:


```
138 verbose type version                                                                                                
139 verbose stack @sentry/utils: No matching version found for @sentry/utils@7.17.0.                                    
139 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)  139 verbose stack     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
140 verbose cwd /opt/iobroker                                                                                           
141 verbose Linux 5.10.103-v7l+                                                                                         
142 verbose node v16.18.0                                                                                               
143 verbose npm  v8.19.2                                                                                                
144 error code ETARGET                                                                                                  
145 error notarget No matching version found for @sentry/utils@7.17.0.                                                  
146 error notarget In most cases you or one of your dependencies are requesting                                         
146 error notarget a package version that doesn't exist.                                                                
147 verbose exit 1                                                                                                      
148 timing npm Completed in 15860ms                                                                                     
149 verbose unfinished npm timer reify 1666875307276                                                                    
150 verbose unfinished npm timer reify:loadTrees 1666875307287                                                          
151 verbose code 1                                                                                                      
152 error A complete log of this run can be found in:                                                                   
152 error     /home/iobroker/.npm/_logs/2022-10-27T12_55_06_822Z-debug-0.log  
```

**Comment by Obast** [comment]
Hier ebenfalls. Adapter arbeitet auch wieder vollständig. Besten Dank!
